services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: ${MSSQL_CONTAINER_NAME}
    user: root
    privileged: true
    env_file:
      - .env
    ports:
      - ${MSSQL_PORT}:${MSSQL_PORT}
    volumes:
      - ${MSSQL_VOLUME}:/var/opt/mssql:delegated
    networks:
      - sample-docker-network

  license:
    image: soulsys/totvs_license:12.1.2410
    container_name: ${LICENSE_CONTAINER_NAME}
    user: root
    privileged: true
    env_file:
      - .env
    ports:
      - ${LICENSE_WEBAPP_PORT}:${LICENSE_WEBAPP_PORT}
    networks:
      - sample-docker-network

  dbaccess:
    image: soulsys/totvs_dbaccess:12.1.2410
    container_name: ${DBACCESS_CONTAINER_NAME}
    user: root
    privileged: true
    env_file:
      - .env
    depends_on:
      - mssql
      - license
    networks:
      - sample-docker-network

  protheus:
    image: soulsys/totvs_protheus:12.1.2410
    container_name: ${PROTHEUS_CONTAINER_NAME}
    user: root
    privileged: true
    env_file:
      - .env
    depends_on:
      - license
      - dbaccess
    ports:
      - ${PROTHEUS_TCP_PORT}:${PROTHEUS_TCP_PORT}
      - ${PROTHEUS_WEBAPP_PORT}:${PROTHEUS_WEBAPP_PORT}
      - ${PROTHEUS_REST_PORT}:${PROTHEUS_REST_PORT}
    volumes:
      - ${PROTHEUS_VOLUME}:/totvs/volume:delegated
    networks:
      - sample-docker-network

networks:
  sample-docker-network:
    external: true
